### ISSUE TITLE
Serializing Portal Items to Pass to My Content

### ISSUE THREAD

**Issue by nohe427** [david-chambers/MiningTheQuartz#13]

**Comment by david-chambers** [comment]
<a href="http://developer.android.com/reference/java/io/Serializable.html">This doc</a> looks like a good starting point .  It's an interface we could add to MainActivity class to serialize the PortalItem object to pass to Content page.  (If we need to).

**Comment by david-chambers** [comment]
<a href="http://www.tutorialspoint.com/java/java_serialization.htm">After more reading</a> wouldn't we only be able to serialize the PortalItem object if the class in the API implements this interface?  It might be better if we made our own class for storing thumbnail, title, and a key value data structure that will get you to the rest of the PortalItem properties?

**Comment by nhaney90** [comment]
Yep

To serialize an object means to convert its state to a byte stream so that the byte stream can be reverted back into a copy of the object. A Java object is serializable if its class or any of its superclasses implements either the java.io.Serializable interface or its subinterface,java.io.Externalizable.
